package com.asksunny.schema.parser;

public enum Keyword {
	CREATE, TABLE, NOT, NULL, PRIMARY, KEY, VARCHAR, NUMBER, INT, BIGINT, INTEGER, 
	DOUBLE, VARCHAR2, BINARY, LONG, DATE, TIME, TIMESTAMP, ALTER, ADD, CONSTRAINT, FOREIGN, IMAGE, TEXT, 
	REFERENCES, DEFAULT, PARTITION, BY, ORDER, SELECT, UPDATE, INSERT, DELETE, FROM, JOIN, ON, WITH, AS, 
	GROUP, HAVING, WHERE, IN, BETWEEN, AND, OR, INDEX, UNIQUE, BYTE, NOPARALLELCREATE, NOPARALLEL, PARALLEL, ASTERISK
}
