package com.asksunny.schema.parser;

public enum Keyword {
	CREATE, DROP, TABLE, CHAR, NOT, NULL, PRIMARY, KEY, VARCHAR, NUMBER, INT, BIGINT, INTEGER, IDENTITY, AUTO_INCREMENT, AUTOINCREMENT, COLUMN_FORMAT, FORMAT,
	DOUBLE, VARCHAR2, BINARY, LONG, DATE, TIME, TIMESTAMP, ALTER, ADD, CONSTRAINT, FOREIGN, IMAGE, TEXT, REFERENCES, DEFAULT, PARTITION, BY, ORDER, SELECT, UPDATE, INSERT, DELETE, FROM, JOIN, ON, WITH, AS, GROUP, HAVING, WHERE, IN, BETWEEN, AND, OR, INDEX, UNIQUE, BYTE, NOPARALLELCREATE, NOPARALLEL, PARALLEL, ASTERISK, NOT_KEYWORD
}
