package com.asksunny.schema.parser;

public enum LexerTokenKind {
	ANNOTATION_COMMENT, EQUAL, COMMENT, DOUBLE_QUOTED_TEXT, SINGLE_QUOTED_TEXT, IDENTIFIER, SEMICOLON, COMMA, LPAREN, RPAREN, NUMBER, KEYWORD, OTHER
}
