package com.asksunny.codegen;

public enum CodeGenType {
	REF, SEQUENCE, DATE, TIME, TIMESTAMP, STRING, FORMATTED_STRING, FIRST_NAME, LAST_NAME, PRICE, LUXURY_PRICE, SSN, STREET, CITY, STATE, ZIP, LONG, INT, DOUBLE, FLOAT, ULONG, UINT, UDOUBLE, UFLOAT, BINARY, BIGINTEGER, BIGDECIMAL, ENUM, OTHER, UUID, IDENTIFIER, USERNAME
}
