package com.asksunny.codegen;

public enum CodeGenAttrName {
	MIN, MAX, VALUES, STEP, FORMAT, VARNAME, LABEL, UITYPE, REF, GROUPLEVEL, ORDER, ITEMSPERPAGE, GROUPFUNCTION, GROUPVIEW, IGNOREVIEW, IGNOREREST, ORDERBY, AUTOGEN, DRILLDOWN
}
